### ISSUE TITLE
OVPN_IOCTL_SET_PEER Windows 11

### ISSUE THREAD

**Issue by joksik** [OpenVPN/ovpn-dco-win#14]
hello i update under Windows 11 21h2 22000.613 drivers for ovpn-dco-win from version 0.6.8 to 0.7.1.
now when i connect with openvpn i have this error in logs:

**DeviceIoControl(OVPN_IOCTL_SET_PEER) failed with code 122**

openvpn seems to be working but using previous drivers i don`t have any errors.

ps: i use openvpn 2.6 git from this link:
https://build.openvpn.net/downloads/temp/ovpn-dco-win/msi/

**Comment by lstipakov** [comment]
Hi,

Version 0.7.1 introduced incompatible API change (setting TCP MSS with SET_PEER) so the client version you use won't work with it. You need the openvpn.exe binary build from the latest dco branch (https://github.com/OpenVPN/openvpn/tree/dco), which could be downloaded from GitHub Actions: https://github.com/OpenVPN/openvpn/suites/6075161490/artifacts/210176397

**Comment by joksik** [comment]
thanks. i download file from github actions and it works. thanks
