### ISSUE TITLE
Doesn't work with `comp_lzo` config

### ISSUE THREAD

**Issue by facboy** [OpenVPN/ovpn-dco-win#17]
~~I can't seem to get any traffic through the interface with `proto tcp` (unfortunately out of my control).  I have another tunnel that uses UDP and that seems to work fine.~~

EDIT: turns out it is having `comp_lzo` forced on by the server, nothing to do with `proto tcp`.

I'm using master `openvpn3` if that makes a difference, on Windows 11.  Not entirely sure where to start troubleshooting.

**Comment by schwabe** [comment]
Correct. I have no plans to include compression with DCO as there are good reasons not to support it. The normal clients still support it for compatibility but also already do not compress if possible.
