### ISSUE TITLE
ovpn-dco

### ISSUE THREAD

**Issue by yxungh** [OpenVPN/ovpn-dco-win#2]
Hi! 
looking forward to… DCO driver,
It should be able to solve the performance problem I have encountered

Will the OpenVPN-GUI  2.6 support ovpn-dco-win?  and ovpn-dco on linux
Is there a plan on when to release it.

**Comment by cron2** [comment]
Hi,

On Thu, Nov 18, 2021 at 11:20:40PM -0800, yxungh wrote:
> Will the OpenVPN-GUI  2.6 support ovpn-dco-win?  and ovpn-dco on linux
> Is there a plan on when to release it.

The plan is to have a 2.6 release around March 2022, with DCO on linux
and windows.

We also plan to have the DCO patches "in" at the end of this year, so we
can ask for testing.

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by yxungh** [comment]
> Hi,
> On Thu, Nov 18, 2021 at 11:20:40PM -0800, yxungh wrote: Will the OpenVPN-GUI 2.6 support ovpn-dco-win? and ovpn-dco on linux Is there a plan on when to release it.
> The plan is to have a 2.6 release around March 2022, with DCO on linux and windows. We also plan to have the DCO patches "in" at the end of this year, so we can ask for testing. gert
> […](#)
> -- "If was one thing all people took for granted, was conviction that if you feed honest figures into a computer, honest figures come out. Never doubted it myself till I met a computer with a sense of humor." Robert A. Heinlein, The Moon is a Harsh Mistress Gert Doering - Munich, Germany ***@***.***


Can I install the DCO separately with openvpn2.x, or must be 2.6-dev,on linux and windows.

**Comment by cron2** [comment]
Hi,

On Thu, Nov 18, 2021 at 11:42:02PM -0800, yxungh wrote:
> Can I install the DCO separately with openvpn2.x, or must be 2.6-dev,on linux and windows.

the kernel driver is separate, but you need support in "openvpn 2.x" - and
that support is not yet integrated.

Then, it will be in "git master", which will become 2.6.0

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by yxungh** [comment]
> the kernel driver is separate, but you need support in "openvpn 2.x" - and that support is not yet integrated.
Now, If I don't use DCO to improve my performance, are there any better other ideas

**Comment by cron2** [comment]
Hi,

On Thu, Nov 18, 2021 at 11:55:06PM -0800, yxungh wrote:
> > the kernel driver is separate, but you need support in "openvpn 2.x" - and that support is not yet integrated.
> Now, If I don't use DCO to improve my performance, are there any better other ideas

That depends on what the actual performance is.  Scalability to more
clients, raw throughput, CPU load, ...

But this is outside the scope of a DCO ticket and should better be 
discussed on the openvpn-users mailing list.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by yxungh** [comment]
ok  thanks
