### ISSUE TITLE
new .msi installer

### ISSUE THREAD

**Issue by joksik** [OpenVPN/ovpn-dco-win#20]
Hello, i test from April OpenVPN-dco under Windows and i always use this official release:
https://build.openvpn.net/downloads/temp/ovpn-dco-win/msi/
but a lot has changed since then (new driver, new API where i must replace files otherwise i have error OVPN_IOCTL_SET_PEER) so for testing purposes it would be good idea to release after 6 months a new test installer that I and others people could just install without needing much intervention for fixing openvpn-dco works with recent changes

**Comment by lstipakov** [comment]
Hi,

You are right, both kernel driver and userspace client code are evolving. You can get the latest installer here: https://github.com/lstipakov/openvpn-build/actions/runs/2902240643

Let me know if it works for you!

**Comment by joksik** [comment]
it`s works ;) thanks a lot!

**Comment by lstipakov** [comment]
Could you describe your setup a bit? OS version etc - we're interested about how dco-win is used. Have you noticed any differences in performance?

**Comment by Fredrik-69** [comment]
I wasn't the one you asked but I just installed the version above and it works like a charm. Thank you!
Windows 11 PRO connecting to an Access Server ver. 2.10.3 unfortunately but it's still much faster than client 2.5.7 with WinTun driver. 

I haven't done any scientific measurements but only copied some large files through SAMBA and I estimate 15-20% faster speeds compared to 2.5.7 WinTun.

Is it still recommended to use tun-mtu 1428 when connecting to a ver. 2.x server?

**Comment by lstipakov** [comment]
Hi @Fredrik-69, thanks for your feedback!

It should not be required to specify `tun-mtu` anymore - we now have a code which calculates crypto and transport overhead and sets TCP MSS accordingly. If I remember correctly, this was a use case why `tun-mtu` was needed.

**Comment by lstipakov** [comment]
@cron2 you asked about testing dco-win patches before merging - there is some feedback here.

**Comment by Fredrik-69** [comment]
> 

Halleluja. I removed tun-mtu & mssfix from my client config and DL speed increased even further. From ~55 Mbps up to average 65-70 Mbps (I'm on a symmteric 1 Gbps line) which is _very_ good for Samba transfers.

You are doing a really great work in your team. 
As soon as the 2.6 client is official we will try out the Linux 3.0 server on an Alma8 Server. Today we have CentOS 7 which isn't compatible with DCO. I really look forward to that day.

**Comment by Fredrik-69** [comment]
Hi @lstipakov. I tried your latest build today with DCO 0.8.0. 
[https://github.com/lstipakov/openvpn-build/actions/runs/2956170238](url)

It works just fine but I was under the impression that _--persist-tun_ would be supported in this build? Unfortunately my Windows 11 installation complains with:

_Options error: --persist-tun is not supported with ovpn-dco._

Have a great day!
/Fredrik

**Comment by lstipakov** [comment]
Yes, this is expected since corresponding client patch (https://patchwork.openvpn.net/project/openvpn2/patch/20220830104958.91-1-lstipakov@gmail.com/) is still waiting for review. 

I have created another [branch](https://github.com/lstipakov/openvpn-build/tree/dco_0.8.0_lstipakov) in my openvpn-build fork which points to my openvpn fork [branch](https://github.com/lstipakov/openvpn/tree/dco_persist_4), which includes `--persist-tun` patch. Installer are available [here](https://github.com/lstipakov/openvpn-build/actions/runs/2965341448), let me know if that works for you.

**Comment by Fredrik-69** [comment]
> Yes, this is expected since corresponding client patch (https://patchwork.openvpn.net/project/openvpn2/patch/20220830104958.91-1-lstipakov@gmail.com/) is still waiting for review.
> 
> I have created another [branch](https://github.com/lstipakov/openvpn-build/tree/dco_0.8.0_lstipakov) in my openvpn-build fork which points to my openvpn fork [branch](https://github.com/lstipakov/openvpn/tree/dco_persist_4), which includes `--persist-tun` patch. Installer are available [here](https://github.com/lstipakov/openvpn-build/actions/runs/2965341448), let me know if that works for you.

Yes, that one works with _persist-tun_. Thank you very much :-)
