### ISSUE TITLE
Dco connect error

### ISSUE THREAD

**Issue by Luke-Honeyball** [OpenVPN/ovpn-dco-win#33]
I am using **port 179 (BDP) with TCP** in order to bypass a firewall, however, I'm getting an error: 
`dco connect error: The semaphore timeout period has expired.   (errno=121)``

It works fine on my home network though.

[full.log](https://github.com/OpenVPN/ovpn-dco/files/10575910/full.log)

**Comment by ordex** [comment]
issue was moved as this is happening on Windows, not Linux.

**Comment by lstipakov** [comment]
Does it work if you add `disable-dco` to the config?

**Comment by Luke-Honeyball** [comment]
I will try that.

**Comment by Luke-Honeyball** [comment]
Now I get this error: TCP: connect to [AF_INET]197.82.214.158:179 failed: Unknown error

**Comment by lstipakov** [comment]
I see, looks like it is not DCO-related, so I am closing this ticket.

**Comment by Luke-Honeyball** [comment]
ok.
