### ISSUE TITLE
Broken DCO data channel when "comp-lzo no" is pushed

### ISSUE THREAD

**Issue by lstipakov** [OpenVPN/ovpn-dco-win#35]
When using Mullvad and dco driver, traffic doesn't flow. No errors in driver or openvpn log. 

Wireshark capture on udp port 1195 shows a lot of traffic to the mullvad server, but almost nothing in another direction except 83 bytes length packets, which are pings according to timestamps.

Looks like Mullval server doesn't like something about data packets generated by dco.

**Comment by lstipakov** [comment]
Same problem with dco on Linux @ordex 

I have attached userland and kernel logs.

[mullvad.log](https://github.com/OpenVPN/ovpn-dco-win/files/10696705/mullvad.log)
[dmesg.log](https://github.com/OpenVPN/ovpn-dco-win/files/10696706/dmesg.log)

**Comment by lstipakov** [comment]
The problem is not related to DCO but Mullvad server sending `comp-lzo no` without client announcing support for compression, which is wrong.

On the client side we should detect that and bail out.

**Comment by schwabe** [comment]
This is not a driver issue. See https://patchwork.openvpn.net/project/openvpn2/patch/20230209142248.455120-1-arne@rfc2549.org/ for details.
