### ISSUE TITLE
FortiEDR breaks UDP upload 

### ISSUE THREAD

**Issue by lstipakov** [OpenVPN/ovpn-dco-win#46]
When FortiEDR filter driver `FortiEDRIotDriver_5.0.3.962.sys` is installed, UDP upload over VPN when using DCO driver is essentially broken.

![dco_udp](https://github.com/OpenVPN/ovpn-dco-win/assets/643110/0d5d53e4-b9c3-4ac8-a96b-8d93f8067656)

The problem is specific to DCO driver and UDP upload. Download speed is fine, also the speed over TCP is fine. Tap-windows6 driver is not affected.

Uninstallation of FortiEDR fixes the problem.

**Comment by cron2** [comment]
Hi,

On Thu, Aug 17, 2023 at 02:58:38AM -0700, Lev Stipakov wrote:
> When FortiEDR filter driver `FortiEDRIotDriver_5.0.3.962.sys` is installed, UDP upload over VPN when using DCO driver is essentially broken.

Sounds like some sort of anti-ddos protection shenanigan... ("no sane
client will produce so much UDP"), though I wonder why tap6 is not
affected...

Of course fortinet's own SSL VPN only does TCP, so they would never
notice.

**Comment by lstipakov** [comment]
The problem has gone away after upgrading FortiEDR to 5.2.0.454. I will close the ticket and if we get details what has been fixed in their driver I'll post it here.
