### ISSUE TITLE
dco support for openvpn server on windows

### ISSUE THREAD

**Issue by homehsu** [OpenVPN/ovpn-dco-win#69]
hi, it seems the ovpn-dco-win is currently supporting windows client only.
would there be any plan to implement for openvpn server on windws as well?
i understand that the demand on windows might be less and less. yet, people like us who built openvpn server on home pc are in need of latest feature like this.
please kidnly advise. thanks.

**Comment by lstipakov** [comment]
We are working on it, but cannot provide exact dates. Tentatively end of the year / beginning of the next year,

**Comment by lstipakov** [comment]
multipeer support is in [multipeer](https://github.com/OpenVPN/ovpn-dco-win/tree/multipeer) branch.

**Comment by cacamille3** [comment]
Hi @lstipakov,

I’ve been testing DCO 2.4.0 on Windows 11 using an OpenVPN build from the current master branch. I made some code changes to prevent DCO from being automatically disabled in server mode (reference: [cacamille3/openvpn](https://github.com/cacamille3/openvpn/tree/dco-win32)).

However, it’s still not working, and I’m encountering the following error:

> DeviceIoControl(OVPN_IOCTL_START_VPN) failed: The handle is invalid. (errno=6)

Is it too early to test this, or am I missing something in my setup?

Thanks in advance for your help!

**Comment by lstipakov** [comment]
The master branch doesn't currently have dco-win server support yet. You would have to use [dco-win-multipeer](https://github.com/lstipakov/openvpn/tree/dco-win-multipeer) branch from my fork.

You could also try the [installer](https://github.com/lstipakov/openvpn-build/actions/runs/11979004209) I've made last week which already includes patched openvpn and dco-win 2.4.0. As for today it contains at least one bug (dco-win is always disabled when TCP transport is selected, even in client mode) which has been fixed in dco-win-multipeer openvpn branch but the fix is not in the installer.

**Comment by cacamille3** [comment]
Thank you for your reply - it looks great!

I conducted some FTP file transfer speed tests using your OpenVPN 2.7 with TAP adapter versus DCO (2.4.0) with OpenVPN as the server on Windows 11. OpenVPN Client using 2.6.12 with DCO in both case.
File size 550MB

- TAP adapter: ~18 MB/s (~30s)
- DCO: ~55 MB/s (~10s)

That's an impressive improvement, great work!

**Comment by lstipakov** [comment]
Some thinks which are not expected to work:
 - TCP transport for the server. Won't happen in the near future.
 - --iroute (when you have a subnet behind the peer and you want other peers to be able to talk to that subnet). I am still figuring out the best way to implement it. The most straightforward would be to perform lookup in routing table from the driver, like we do in Linux and FreeBSD, but there seem to be no public API in Windows kernel to do it, which was also somewhat confirmed by MSFT folks. If this truly won't be possible we would have to implement internal routing table and lookup in the driver itself, like we do it userspace openvpn. Anyway, this should be fixed before 2.7.
 - Global stats and per-peer stats. A relatively small thing, will certainly be implemented soon.

**Comment by lstipakov** [comment]
Thank you, this is encouraging indeed.

**Comment by cacamille3** [comment]
I also wanted to do some test on Windows Server 2016 on a different VM but it is not DCO compatible.
I then tested different version of the TAP adapter:

- 9.27.0 => ~18 MB/s
- 9.26.0 (not tested yet but supposedly similar to version 9.27.0)
- 9.25.0 (not tested yet but supposedly similar to version 9.24.7)
- 9.24.7 => ~36 MB/s
- 9.24.6 => ~18 MB/s

Any idea why there was a performance improvement with 9.24.7 that was removed afterwards ?
Maybe this change ?  [rxpath: fix broken TCP connections on Windows Server](https://github.com/OpenVPN/tap-windows6/commit/eb764efe1579dc0d9d64a64186b16491af37de88) 

This change seems to have been reverted in 9.26.0
I found the following info in the OpenVPN 2.6.3 but without details about the BSODs or the scenarios...

> Note: Windows MSI was updated to I003 on April 27th. Changes in I003:
> 
> Update include tap-windows6 driver to 9.26.0
> Revert fix for occasional TCP performance degradation on Windows Server 2022 (GH [​tap-windows6#147](https://github.com/OpenVPN/tap-windows6/pull/147)) since users reported BSODs in some (undetermined) scenarios.

**Comment by lstipakov** [comment]
Yes, that was the case. By some reasons I cannot find more details, but this must be in one of our github projects or trac (not sure if we already migrated issues to GH back then).
