### ISSUE TITLE
The driver is not available

### ISSUE THREAD

**Issue by yxungh** [OpenVPN/ovpn-dco-win#8]
I m compiling ovpn-dco-win in vs2019 and using devcon to install ovpn-dco.sys
But don't work
![image](https://user-images.githubusercontent.com/49184832/149090947-f8ddc281-8ac1-4c08-90fa-3abe3fdc95bf.png)

**Comment by yxungh** [comment]
@lstipakov Is there a problem with the driver itself or is it an inf file？

**Comment by lstipakov** [comment]
The driver should be ok, it is hard to say what could be wrong without seeing logs. Did you build with EWDK? Could you try with binaries from Github Actions? Did you enable test signing?

**Comment by yxungh** [comment]
> The driver should be ok, it is hard to say what could be wrong without seeing logs. Did you build with EWDK? Could you try with binaries from Github Actions? Did you enable test signing?

The first time I generated the ovpn-dco.sys directly using vs2019.

Now I mount the EWDK, running
msbuild /p:platform=x64 /p:configuration=release /p:signmode=off ovpn-dco-win.vcxproj /t:Build

then devcon install ovpn-dco.sys ovpn-dco, In system test mode
The result will also be reported wrong.

![%43EFCWN$ENXH6}4IHS}E Q](https://user-images.githubusercontent.com/49184832/149608997-c88ce889-33cb-4c23-9da0-7b62ce5bc1b5.png)

![HFTY HUK916Z()VJX4IUUPR](https://user-images.githubusercontent.com/49184832/149608973-f7050774-1896-43ed-ab20-8fffd290b286.png)

but In the windows server2016 ,the program input point cannot be found

May I have anything else I didn't notice, thank you

**Comment by lstipakov** [comment]
I am not sure it will work without signing. Could you try with debug signing? 

Lähetetty iPhonesta

**Comment by yxungh** [comment]
> I am not sure it will work without signing. Could you try with debug signing? 

build with EWDK，running msbuild /p:platform=x64 /p:configuration=debug /P:signmode=TestSign ovpn-dco-win.vcxproj /t:Build
The same error will be reported，The Windows could not load the device driver for this hardware, errcode=39

I think using EWDK is the same as using IDE, Binary is the same.

Can you tell me about your environment and how you compile it,
I'll compare the differences.

**Comment by lstipakov** [comment]
Let's make sure that your test environment is configured correctly. You should be able to install driver, debug-built by GitHub Actions, https://github.com/OpenVPN/ovpn-dco-win/suites/4784019087/artifacts/133614882

Can you check if that works for you? If not, C:\Windows\INF\setupapi.dev.log should have some clues.

**Comment by yxungh** [comment]
Thank you for your help!!!
I really wanted to test the performance of the drive.

But you sent me .sys,the same problem exists,

err info:
The Windows could not load the device driver for this hardware.The driver may be damaged or missing.(Code # 39)
{Driver input point was not found}

The setupapi.dev.log shows 

`
[Boot Session: 2022/01/17 21:24:52.495]
>>>  [Device Install (UpdateDriverForPlugAndPlayDevices) - ovpn-dco]
>>>  Section start 2022/01/17 21:31:18.238
      cmd: devcon.exe  install "C:\Program Files\ovpn-dco\driver\ovpn-dco.inf" ovpn-dco
     ndv: INF path: C:\Program Files\ovpn-dco\driver\ovpn-dco.inf
     ndv: Install flags: 0x00000001
     ndv: {Update Device Driver - ROOT\NET\0000}
     ndv:      Search options: 0x00000080
     ndv:      Searching single INF 'C:\Program Files\ovpn-dco\driver\ovpn-dco.inf'
     dvi:      {Build Driver List} 21:31:18.269
     dvi:           Searching for hardware ID(s):
     dvi:                ovpn-dco
     dvi:           Created Driver Node:
     dvi:                HardwareID   - ovpn-dco
     dvi:                InfName      - c:\program files\ovpn-dco\driver\ovpn-dco.inf
     dvi:                DevDesc      - OpenVPN Data Channel Offload
     dvi:                Section      - ovpn-dco_Device.NT
     dvi:                Rank         - 0x80ff0000
     dvi:                Signer Score - Not digitally signed
     dvi:                DrvDate      - 12/29/2021
     dvi:                Version      - 9.9.24.260
     dvi:      {Build Driver List - exit(0x00000000)} 21:31:18.425
     dvi:      {DIF_SELECTBESTCOMPATDRV} 21:31:18.425
     dvi:           Default installer: Enter 21:31:18.425
     dvi:                {Select Best Driver}
     dvi:                     Class GUID of device changed to: {4d36e972-e325-11ce-bfc1-08002be10318}.
     dvi:                     Selected:
     dvi:                          Description - [OpenVPN Data Channel Offload]
     dvi:                          InfFile     - [c:\program files\ovpn-dco\driver\ovpn-dco.inf]
     dvi:                          Section     - [ovpn-dco_Device]
     dvi:                {Select Best Driver - exit(0x00000000)}
     dvi:           Default installer: Exit
     dvi:      {DIF_SELECTBESTCOMPATDRV - exit(0x00000000)} 21:31:18.441
     ndv:      Forcing driver install:
     ndv:           Inf Name       - ovpn-dco.inf
     ndv:           Driver Date    - 12/29/2021
     ndv:           Driver Version - 9.9.24.260
     sto:      {Setup Import Driver Package: c:\program files\ovpn-dco\driver\ovpn-dco.inf} 21:31:18.456
     sto:           Driver package already imported as 'oem76.inf'.
     sto:      {Setup Import Driver Package - exit (0x00000000)} 21:31:18.456
     dvi:      Searching for hardware ID(s):
     dvi:           ovpn-dco
     dvi:      Class GUID of device changed to: {4d36e972-e325-11ce-bfc1-08002be10318}.
     dvi:      {Plug and Play Service: Device Install for ROOT\NET\0000}
     ndv:           Driver INF Path: C:\Windows\INF\oem76.inf
     ndv:           Driver Node Name: ovpn-dco.inf:c695c3de07ba2b5d:ovpn-dco_Device:9.9.24.260:ovpn-dco
     ndv:           Driver Store Path: C:\Windows\System32\DriverStore\FileRepository\ovpn-dco.inf_amd64_ecf8a55d35d4908e\ovpn-dco.inf
     dvi:           Searching for hardware ID(s):
     dvi:                ovpn-dco
     dvi:           Class GUID of device changed to: {4d36e972-e325-11ce-bfc1-08002be10318}.
     ndv:           {Core Device Install} 21:31:18.628
     ndv:                {Install Device - ROOT\NET\0000} 21:31:18.628
     ndv:                     Parent device: HTREE\ROOT\0
     ndv:                     {Configure Device - ROOT\NET\0000} 21:31:18.644
     ndv:                          Parent device: HTREE\ROOT\0
     sto:                          {Configure Driver Package: C:\Windows\System32\DriverStore\FileRepository\ovpn-dco.inf_amd64_ecf8a55d35d4908e\ovpn-dco.inf}
     sto:                               Source Filter  = ovpn-dco
     inf:                               Class GUID     = {4d36e972-e325-11ce-bfc1-08002be10318}
     inf:                               Class Options  = Configurable
     inf:                               {Configure Driver: OpenVPN Data Channel Offload}
     inf:                                    Section Name = ovpn-dco_Device.NT
     inf:                                    {Add Service: ovpn-dco}
     inf:                                         Start Type    = 3
     inf:                                         Service Type  = 1
     inf:                                         Error Control = 1
     inf:                                         Image Path    = \SystemRoot\System32\drivers\ovpn-dco.sys
     inf:                                         Display Name  = ovpn-dco
     inf:                                         Updated service 'ovpn-dco'.
     inf:                                    {Add Service: exit(0x00000000)}
     inf:                                    Hardware Id  = ovpn-dco
     inf:                                    {Configure Driver Configuration: ovpn-dco_Device.NT}
     inf:                                         Service Name  = ovpn-dco
     inf:                                         Config Flags  = 0x00000000
     inf:                                    {Configure Driver Configuration: exit(0x00000000)}
     inf:                               {Configure Driver: exit(0x00000000)}
     flq:                               Copying 'C:\Windows\System32\DriverStore\FileRepository\ovpn-dco.inf_amd64_ecf8a55d35d4908e\ovpn-dco.sys' to 'C:\Windows\System32\drivers\ovpn-dco.sys'.
     cpy:                               Existing file 'C:\Windows\System32\drivers\ovpn-dco.sys' remains unchanged.
     sto:                          {Configure Driver Package: exit(0x00000000)}
     dvi:                          Install Device: Configuring device (oem76.inf:ovpn-dco,ovpn-dco_Device.NT). 21:31:20.488
     dvi:                          Install Device: Configuring device completed. 21:31:20.503
     dvi:                          Install Device: Starting device. 21:31:20.503
     dvi:                          Install Device: Starting device completed. 21:31:20.534
!!!  dvi:                          Device not started: Device has problem: 0x27 (CM_PROB_DRIVER_FAILED_LOAD), problem status: 0xc0000263.
     ndv:                     {Configure Device - exit(0x00000000)} 21:31:20.534
!    ndv:                     Queueing up error report since device has a PnP problem...
     ndv:                {Install Device - exit(0x00000000)} 21:31:20.847
     ndv:           {Core Device Install - exit(0x00000000)} 21:31:20.847
     ump:      {Plug and Play Service: Device Install exit(00000000)}
     ndv: {Update Device Driver - exit(00000000)}
<<<  Section end 2022/01/17 21:31:20.894
<<<  [Exit status: SUCCESS]
`


> Let's make sure that your test environment is configured correctly. You should be able to install driver, debug-built by GitHub Actions, https://github.com/OpenVPN/ovpn-dco-win/suites/4784019087/artifacts/133614882
> 
> Can you check if that works for you? If not, C:\Windows\INF\setupapi.dev.log should have some clues.

**Comment by yxungh** [comment]
@lstipakov   Thanks!
When the ovpn-dco-win plans to release?
At present, it is not a fool for all systems.

**Comment by lstipakov** [comment]
Let's make sure your system is clean from any previously installed drivers.

1) Delete ovpn-dco device by running
`devcon.exe remove ovpn-dco.inf ovpn-dco`
2) Find all previously installed ovpn-dco drivers
`pnputil /enum-drivers`, 
This should print you list of all installed drivers, find those with
```
Published Name:     oem<x>.inf
Original Name:      ovpn-dco.inf
Provider Name:      OpenVPN, Inc
```
(there could be more than one)
3)  For each driver found at previous step, run
`pnputil /delete-driver oem<x>.inf`

And then try again to install the driver from GitHub Actions. I just tested that it workson WIndows Server 2022 (21H2, 20348), but should also work on Windows 10 20H1 and newer.

**Comment by lstipakov** [comment]
You could also try WHQL-signed version built from the latest master
[Signed_1152921505694339831.zip](https://github.com/OpenVPN/ovpn-dco-win/files/7882464/Signed_1152921505694339831.zip)

**Comment by yxungh** [comment]
I tried it again and clean all previously installed drivers. There should be multiple ones at the same time.
Also is the errcode 39,

But the system that I am using right now is windows server2016.

> Let's make sure your system is clean from any previously installed drivers.

**Comment by cron2** [comment]
Hi,

On Mon, Jan 17, 2022 at 06:46:24AM -0800, yxungh wrote:
> But the system that I am using right now is windows server2016.

Too old, if I understand this right.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by lstipakov** [comment]
The minimum supported version is Windows 10 20H1 and Windows Server 2022. 

Lähetetty iPhonesta

**Comment by yxungh** [comment]
I ve tried compiling it using EWDK myself.
In 20H2, in the virtual machine, but he is 32-bit
the error
![image](https://user-images.githubusercontent.com/49184832/149794423-334da75e-ad8a-4496-ad4b-4808b8ac1c3f.png)

Tomorrow I'll get a high version 64-bit machine to try it signed,and give you feedback
thanks

> The minimum supported version is Windows 10 20H1 and Windows Server 2022. Lähetetty iPhonesta
> […](#)
> Gert Doering ***@***.***> kirjoitti 17.1.2022 kello 16.55: ﻿ Hi, On Mon, Jan 17, 2022 at 06:46:24AM -0800, yxungh wrote: > But the system that I am using right now is windows server2016. Too old, if I understand this right. gert -- "If was one thing all people took for granted, was conviction that if you feed honest figures into a computer, honest figures come out. Never doubted it myself till I met a computer with a sense of humor." Robert A. Heinlein, The Moon is a Harsh Mistress Gert Doering - Munich, Germany ***@***.*** — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.

**Comment by yxungh** [comment]
It is indeed a problem with the system version, thanks
